### ISSUE TITLE
Vimeo Problems

### ISSUE THREAD

**Issue by irmerk** [accordproject/technical-steering-committee#17]
# Discussion 🗣
We seem to have lost access to our Vimeo account, see:
- https://github.com/accordproject/techdocs/issues/327
- https://github.com/accordproject/techdocs/issues/328
- https://github.com/accordproject/techdocs/issues/329

## Context
Vimeo is where we host all of our video content

**Comment by jeromesimeon** [comment]
@irmerk I believe this is resolved?

**Comment by irmerk** [comment]
Unsure, I'll look more into this because the links in those issues are still broken I believe.

**Comment by jeromesimeon** [comment]
> # Discussion 🗣
> We seem to have lost access to our Vimeo account, see:
> 
> * [accordproject/techdocs#327](https://github.com/accordproject/techdocs/issues/327)
> * [accordproject/techdocs#328](https://github.com/accordproject/techdocs/issues/328)
> * [accordproject/techdocs#329](https://github.com/accordproject/techdocs/issues/329)
> 
> ## Context
> Vimeo is where we host all of our video content

**Comment by jeromesimeon** [comment]
> Unsure, I'll look more into this because the links in those issues are still broken I believe.

Only the first link is a video and it works for me:

<img width="1012" alt="Screenshot 2021-01-19 at 6 49 32 PM" src="https://user-images.githubusercontent.com/670099/105107978-4171e480-5a87-11eb-9f4b-3400907ad962.png">

**Comment by irmerk** [comment]
Both accordproject/techdocs#328 and accordproject/techdocs#329 are broken, unsure if they are video links.

**Comment by martinhalford** [comment]
Fixed.
